In [3]:
import numpy as np
import pandas as pd

In [3]:
import pdb; 

def main(file_path):
    file = open(file_path)
    T, P = map(int, file.readline().split(' '))
    c = 2*np.eye(int(T))
    res = np.array(T)

    b = [1 for _ in range(T)]

    for line in file:
        e1, g1, e2, g2 = map(int, line.split()[1:5])
        c[e1-1][e2-1] -= 1
        c[e2-1][e1-1] -= 1
        c[e1-1][e1-1] += 1
        c[e2-1][e2-1] += 1
        #pdb.set_trace()
        if g1 > g2:
            b[e1-1] += 0.5
            b[e2-1] -= 0.5
        else:
            b[e2-1] += 0.5
            b[e1-1] -= 0.5
    return np.linalg.solve(c, b)

In [2]:
import re
import os
import subprocess
test_files = os.listdir('../tests/')
tests = [re.match(r"(.*)\.in$", file)[1] for file in os.listdir('../tests/') if re.match(r".*\.in$", file) is not None]
r = {}
r_ref = {}
for test in tests:
    test_in = f'../tests/{test}.in'
    test_out = f'../tests/{test}.out'
    test_expected = f'../tests/{test}.expected'
    if f'{test}.out' not in test_files:
        subprocess.run(['../tp', test_in, test_out, '0'])
    if f'{test}.expected' not in test_files:
        r_ref[test] = main(test_in)
        with open(test_expected, 'w') as expected_file:
            expected_file.write('\n'.join(str(value) for value in r_ref[test]))
    with open(test_out) as res:
            r[test] = [float(line) for line in res]
    with open(test_expected) as res:
            r_ref[test] = [float(line) for line in res]

test = 'prueba1'
print(r[test], r_ref[test])

SyntaxError: invalid syntax (<ipython-input-2-0e5288ad306f>, line 9)

In [24]:
a = np.array([
[2.44949, 0, 0, 0, 0, 0],
[-0, 2.44949, 0, 0, 0, 0],
[-0.816497, -0.408248, 2.27303, 0, 0, 0],
[-0.816497, -0, -0.733236, 2.40743, 0, 0],
[-0, -0.408248, -0.0733236, -0.437714, 2.3741, 0],
[-0, -0.816497, -0.146647, -0.460046, -1.07218, 2.225]]) 
b = np.array([
[2.44949, 0, 0, 0, 0, 0],
[-0, 2.44949, 0, 0, 0, 0],
[-0.816497, -0.408248, 2.3094, 0, 0, 0],
[-0.816497, -0, -0.721688, 2.51661, 0, 0],
[-0, -0.408248, -0, -0.39736, 2.41523, 0],
[-0, -0.816497, -0, -0.39736, -0.966092, 2.48504]]).T



In [9]:
a*b

array([[ 6.00000126,  0.        , -0.        , -0.        ,  0.        ,
         0.        ],
       [ 0.        ,  6.00000126, -0.        ,  0.        , -0.        ,
        -0.        ],
       [-0.        , -0.        ,  5.33332836, -0.        ,  0.        ,
         0.        ],
       [-0.        ,  0.        , -0.        ,  6.33332589, -0.        ,
        -0.        ],
       [ 0.        , -0.        ,  0.        , -0.        ,  5.83333595,
        -0.        ],
       [ 0.        , -0.        ,  0.        , -0.        , -0.        ,
         6.1754238 ]])

In [25]:

ch = np.linalg.cholesky(np.array([
[6, -0, -2, -2, -0, -0],
[-0, 6, -1, -0, -1, -2],
[-2, -1, 6, -1, -0, -0],
[-2, -0, -1, 7, -1, -1],
[-0, -1, -0, -1, 6, -2],
[-0, -2, -0, -1, -2, 7]]))
print(ch)
print(a)

[[ 2.44948974  0.          0.          0.          0.          0.        ]
 [ 0.          2.44948974  0.          0.          0.          0.        ]
 [-0.81649658 -0.40824829  2.27303028  0.          0.          0.        ]
 [-0.81649658  0.         -0.73323558  2.40742579  0.          0.        ]
 [ 0.         -0.40824829 -0.07332356 -0.43771378  2.3741027   0.        ]
 [ 0.         -0.81649658 -0.14664712 -0.46004612 -1.07217541  2.22500009]]
[[ 2.44949    0.         0.         0.         0.         0.       ]
 [ 0.         2.44949    0.         0.         0.         0.       ]
 [-0.816497  -0.408248   2.27303    0.         0.         0.       ]
 [-0.816497   0.        -0.733236   2.40743    0.         0.       ]
 [ 0.        -0.408248  -0.0733236 -0.437714   2.3741     0.       ]
 [ 0.        -0.816497  -0.146647  -0.460046  -1.07218    2.225    ]]


In [30]:
a.dot(a.T)

array([[ 6.00000126e+00,  0.00000000e+00, -2.00000124e+00,
        -2.00000124e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  6.00000126e+00, -9.99999394e-01,
         0.00000000e+00, -9.99999394e-01, -2.00000124e+00],
       [-2.00000124e+00, -9.99999394e-01,  5.99999916e+00,
        -1.00000007e+00, -3.13004000e-07,  2.36846000e-07],
       [-2.00000124e+00,  0.00000000e+00, -1.00000007e+00,
         7.00002159e+00, -1.00000231e+00, -1.00000168e+00],
       [ 0.00000000e+00, -9.99999394e-01, -3.13004000e-07,
        -1.00000231e+00,  5.99998714e+00, -2.00000801e+00],
       [ 0.00000000e+00, -2.00000124e+00,  2.36846000e-07,
        -1.00000168e+00, -2.00000801e+00,  7.00000997e+00]])